image: "python:3.8"

before_script:
  - python --version
  - pip install flake8==3.8.3

stages:
  - Static Analysis

flake8:
  stage: Static Analysis
  script:
  - flake8 --max-line-length=120 --exclude migrations
