version: '3'

services:
  web:
    container_name: web
    restart: unless-stopped
    build:
      context: ./platform_code
      dockerfile: Dockerfile.prod
    command: gunicorn dev_platform.wsgi:application --bind 0.0.0.0:8000 --workers=4 --timeout 10
    networks:
      - main
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:latest
    networks:
      - main
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod

  nginx:
     container_name: nginx
     image: nginx:latest
     restart: unless-stopped
     ports:
       - "80:80"
     networks:
       - main
     volumes:
       - static_volume:/home/app/web/static
       - ./data/nginx/nginx-prod-like-local.conf:/etc/nginx/nginx.conf
     depends_on:
       - web

volumes:
  postgres_data:
  static_volume:

networks:
  main:
