version: '3'

services:
  web:
    build: ./platform_code
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    # command: sh -c "python manage.py makemigrations --merge &&
    #                 python manage.py migrate &&
    #                 python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - ./platform_code/:/code
    env_file:
      - ./.env.dev
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    container_name: postgres

volumes:
  postgres_data: