[tool.black]
line-length = 95
exclude = '''
/(
    \.eggs
  | \.git
  | \.venv
  | build
  | dist
  | migrations
)/
'''

[tool.isort]
include_trailing_comma = true
line_length = 95
multi_line_output = 3
skip = ["./.venv"]
skip_glob = ["**/migrations/*","**/templates/*"]
known_third_party = []
use_parentheses = true

[tool.pyright]
include = ["*"]
exclude = ["**/migrations/*","**/templates/*","./.venv/"]
