# Generated by Django 3.0.5 on 2020-10-29 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201022_1306'),
        ('home', '0003_auto_20201026_1553'),
    ]

    operations = [
    ]
