# Generated by Django 3.2.7 on 2021-10-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210719_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformmanagement',
            name='labelling_threshold',
            field=models.FloatField(default=45),
        ),
    ]
