# Generated by Django 3.0.5 on 2020-11-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_merge_20201029_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='hide_membership',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('read_only', 'read_only'), ('editor', 'editor'), ('admin', 'admin')], default='admin', max_length=200),
        ),
    ]
