# Generated by Django 3.0.5 on 2020-11-05 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201104_1659'),
        ('home', '0005_auto_20201104_1433'),
    ]

    operations = [
    ]
