# Generated by Django 3.2.7 on 2022-05-02 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_footer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['name', '-created_at']},
        ),
    ]
