# Generated by Django 3.2.7 on 2022-05-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_organisation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='footer',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
