# Generated by Django 3.2.7 on 2023-10-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220503_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformmanagement',
            name='app_logo',
            field=models.ImageField(blank=True, null=True, upload_to='app_logo'),
        ),
        migrations.AddField(
            model_name='platformmanagement',
            name='font_family',
            field=models.CharField(default='Ubuntu', max_length=100),
        ),
        migrations.AddField(
            model_name='platformmanagement',
            name='primary_color',
            field=models.CharField(default='5550FF', max_length=7),
        ),
        migrations.AddField(
            model_name='platformmanagement',
            name='primary_color_light',
            field=models.CharField(default='726EF5', max_length=7),
        ),
        migrations.AddField(
            model_name='platformmanagement',
            name='secondary_color',
            field=models.CharField(default='FCE180', max_length=7),
        ),
        migrations.AddField(
            model_name='platformmanagement',
            name='secondary_color_light',
            field=models.CharField(default='FAE8A7', max_length=7),
        ),
        migrations.AddField(
            model_name='platformmanagement',
            name='tertiary_color',
            field=models.CharField(default='91D3FF', max_length=7),
        ),
        migrations.AddField(
            model_name='platformmanagement',
            name='tertiary_color_light',
            field=models.CharField(default='B8DFFA', max_length=7),
        ),
        migrations.AddField(
            model_name='platformmanagement',
            name='text_color',
            field=models.CharField(default='4D566B', max_length=7),
        ),
        migrations.AddField(
            model_name='platformmanagement',
            name='text_color_light',
            field=models.CharField(default='70788B', max_length=7),
        ),
    ]
