# Generated by Django 3.2.7 on 2023-10-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20231006_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage_text', models.TextField()),
            ],
        ),
    ]
