# Generated by Django 3.0.5 on 2021-01-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20201208_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.BooleanField(default=False)),
                ('delivery_text', models.TextField(max_length=1000)),
                ('delivery_text_en', models.TextField(max_length=1000, null=True)),
                ('delivery_text_fr', models.TextField(max_length=1000, null=True)),
                ('languages_activation', models.BooleanField(default=False)),
            ],
        ),
    ]
