# Generated by Django 3.2.7 on 2023-10-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_platformtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformtext',
            name='homepage_text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='platformtext',
            name='homepage_text_fr',
            field=models.TextField(null=True),
        ),
    ]
