# Generated by Django 3.0.5 on 2021-01-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_platformmanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformmanagement',
            name='delivery_text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='platformmanagement',
            name='delivery_text_en',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='platformmanagement',
            name='delivery_text_fr',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
