# Generated by Django 3.0.5 on 2021-01-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210121_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformmanagement',
            name='delivery_text',
        ),
        migrations.AlterField(
            model_name='platformmanagement',
            name='delivery_text_en',
            field=models.TextField(default='Mise à jour de la plateforme en cours', max_length=1000),
        ),
        migrations.AlterField(
            model_name='platformmanagement',
            name='delivery_text_fr',
            field=models.TextField(default='Platform update ongoing', max_length=1000),
        ),
    ]
