# Generated by Django 3.0.5 on 2021-02-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210121_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformmanagement',
            name='activate_multi_languages',
            field=models.BooleanField(default=False, help_text='This should not be activated if an assessment does not exist both in French and English'),
        ),
    ]
