# Generated by Django 3.0.5 on 2021-02-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210202_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language_preference',
            field=models.CharField(default='fr', max_length=10),
        ),
    ]
