# Generated by Django 3.0.5 on 2021-02-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20210211_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('text_en', models.TextField(null=True)),
                ('text_fr', models.TextField(null=True)),
                ('version', models.CharField(max_length=150)),
            ],
        ),
    ]
