# Generated by Django 3.0.5 on 2021-02-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20210211_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('read_only', 'read only'), ('editor', 'editor'), ('admin', 'admin')], default='admin', max_length=200),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='sector',
            field=models.CharField(choices=[('Industriel - Grande entreprise', 'Industrial - Large company'), ('Industriel - ETI', 'Industrial - Mid-sized company'), ('Industriel - PME', 'Small and Medium-Sized Businesses'), ('Prestataire B2B - Editeur de logiciels', 'B2B Service Provider - Software publisher'), ('Prestataire B2B - Cabinet de conseil', 'B2B service provider - Consulting agency'), ('Organisme de recherche', 'Research organisation'), ('autres', 'Other')], max_length=1000),
        ),
    ]
