# Generated by Django 3.0.5 on 2021-03-03 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_releasenote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='language_preference',
        ),
    ]
