# Generated by Django 3.0.5 on 2021-03-22 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20210226_1059'),
        ('home', '0020_remove_user_language_preference'),
    ]

    operations = [
    ]
