# Generated by Django 3.0.5 on 2021-03-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_user_language_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='fr', max_length=5),
        ),
    ]
