# Generated by Django 3.0.5 on 2021-03-23 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_merge_20210322_1627'),
        ('home', '0021_user_language_preference'),
    ]

    operations = [
    ]
