# Generated by Django 3.0.5 on 2020-07-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0009_auto_20200626_0844"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluation",
            name="name",
            field=models.CharField(default="Evaluation 02/07/2020", max_length=200),
        ),
        migrations.AlterField(
            model_name="section",
            name="user_progression",
            field=models.IntegerField(default=0),
        ),
    ]
