# Generated by Django 3.0.5 on 2020-07-02 13:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0009_auto_20200626_0844"),
    ]

    operations = [
        migrations.AddField(
            model_name="masterchoice",
            name="depends_on",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assessment.MasterChoice",
            ),
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="name",
            field=models.CharField(default="Evaluation 2020-07-02", max_length=200),
        ),
        migrations.CreateModel(
            name="ScoringSystem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                (
                    "organisation_type",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "master_choices_weight_json",
                    django.contrib.postgres.fields.jsonb.JSONField(),
                ),
                ("coefficient", models.FloatField(blank=True, null=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessment.Assessment",
                    ),
                ),
            ],
        ),
    ]
