# Generated by Django 3.0.5 on 2020-07-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0010_auto_20200702_1947"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=2000)),
                ("link", models.TextField(max_length=2000)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("resource", "resource"),
                            ("explication", "explication"),
                        ],
                        default="resource",
                        max_length=500,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="masterevaluationelement", name="resource_text",
        ),
        migrations.AlterField(
            model_name="evaluation",
            name="name",
            field=models.CharField(default="Evaluation 03/07/2020", max_length=200),
        ),
        migrations.AddField(
            model_name="masterevaluationelement",
            name="explanation_links",
            field=models.ManyToManyField(
                blank=True,
                related_name="explanation_links",
                to="assessment.ExternalLink",
            ),
        ),
        migrations.AddField(
            model_name="masterevaluationelement",
            name="resources",
            field=models.ManyToManyField(
                blank=True, related_name="resources", to="assessment.ExternalLink"
            ),
        ),
    ]
