# Generated by Django 3.0.5 on 2020-07-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0011_auto_20200703_0827"),
    ]

    operations = [
        migrations.AddField(
            model_name="externallink",
            name="additional_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
