name: Project CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

env:
  SECRET_KEY: test
  SQL_USER: postgres
  SQL_PASSWORD: postgres
  SQL_DATABASE: postgres
  DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      postgres_main:
        image: postgres:latest
        env:
        - POSTGRES_USER: postgres
        - POSTGRES_PASSWORD: postgres
        - POSTGRES_BD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r platform_code/requirements.txt

      - name: Lint
        run: |
          python platform_code/manage.py check --deploy
          pre-commit run --all-files --show-diff-on-failure

      - name: Set up Django
        run: |
          python platform_code/manage.py makemigrations
          python platform_code/manage.py migrate

      - name: Run Tests
        env:
          DEBUG: "True"
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"
        run: |
          python platform_code/manage.py test
