name: Project CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      image: postgres:latest
      env:
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: postgres
      - POSTGRES_BD: postgres
      ports:
      - 5432:5432
      options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.8.0-alpine
          uses: actions/setup-python@v3
          with:
            python-version: 3.8.0-alpine

        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Lint
          run: |
            python manage.py check --deploy
            pre-commit run --all-files --show-diff-on-failure

        - name: Set up Django
          run: |
            python manage.py makemigrations
            python manage.py migrate

        - name: Run Tests
          env:
            SECRET_KEY: "test"
            DEBUG: "True"
            DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"
          run: |
            python manage.py test
