# Generated by Django 3.0.5 on 2021-03-23 13:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_fr', models.CharField(max_length=100, null=True)),
                ('version', models.CharField(default='mvp', max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ticked', models.BooleanField(default=False)),
                ('fetch', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Evaluation', max_length=200)),
                ('slug', models.SlugField()),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Assessment')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=4000)),
                ('text_en', models.TextField(blank=True, max_length=4000, null=True)),
                ('text_fr', models.TextField(blank=True, max_length=4000, null=True)),
                ('type', models.CharField(default='Web article', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MasterChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('answer_text_en', models.TextField(null=True)),
                ('answer_text_fr', models.TextField(null=True)),
                ('order_id', models.CharField(blank=True, max_length=200, null=True)),
                ('is_concerned_switch', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_fr', models.CharField(max_length=200, null=True)),
                ('keyword', models.CharField(blank=True, max_length=100, null=True)),
                ('keyword_en', models.CharField(blank=True, max_length=100, null=True)),
                ('keyword_fr', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.Assessment')),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upgrade_json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('final_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_assessment', to='assessment.Assessment')),
                ('origin_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_assessment', to='assessment.Assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_progression', models.IntegerField(default=0)),
                ('points', models.FloatField(default=0)),
                ('max_points', models.FloatField(blank=True, default=0, null=True)),
                ('fetch', models.BooleanField(default=True)),
                ('user_notes', models.TextField(blank=True, max_length=20000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.Evaluation')),
                ('master_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.MasterSection')),
            ],
        ),
        migrations.CreateModel(
            name='ScoringSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('organisation_type', models.CharField(blank=True, default='entreprise', max_length=1000, null=True)),
                ('master_choices_weight_json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('attributed_points_coefficient', models.FloatField(default=0.5)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Assessment')),
            ],
        ),
        migrations.CreateModel(
            name='MasterEvaluationElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('name_en', models.CharField(blank=True, max_length=1000, null=True)),
                ('name_fr', models.CharField(blank=True, max_length=1000, null=True)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('question_text', models.TextField()),
                ('question_text_en', models.TextField(null=True)),
                ('question_text_fr', models.TextField(null=True)),
                ('question_type', models.CharField(choices=[('radio', 'radio'), ('checkbox', 'checkbox')], default='radio', max_length=200)),
                ('explanation_text', models.TextField(blank=True, null=True)),
                ('explanation_text_en', models.TextField(blank=True, null=True)),
                ('explanation_text_fr', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depends_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditioned_by', to='assessment.MasterChoice')),
                ('external_links', models.ManyToManyField(blank=True, related_name='external_links', to='assessment.ExternalLink')),
                ('master_section', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.MasterSection')),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
        migrations.AddField(
            model_name='masterchoice',
            name='master_evaluation_element',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.MasterEvaluationElement'),
        ),
        migrations.CreateModel(
            name='EvaluationScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need_to_set_max_points', models.BooleanField(default=False)),
                ('need_to_calculate', models.BooleanField(default=True)),
                ('max_points', models.FloatField(blank=True, default=0, null=True)),
                ('coefficient_scoring_system', models.FloatField(blank=True, default=0, null=True)),
                ('points_not_concerned', models.FloatField(blank=True, default=0, null=True)),
                ('points_obtained', models.FloatField(blank=True, default=0, null=True)),
                ('points_to_dilate', models.FloatField(blank=True, default=0, null=True)),
                ('dilatation_factor', models.FloatField(blank=True, default=0, null=True)),
                ('score', models.FloatField(blank=True, default=0, null=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationElementWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('organisation_type', models.CharField(blank=True, default='entreprise', max_length=1000, null=True)),
                ('master_evaluation_element_weight_json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Assessment')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_notes', models.TextField(blank=True, max_length=20000, null=True)),
                ('status', models.BooleanField(default=False)),
                ('points', models.FloatField(default=0)),
                ('max_points', models.FloatField(blank=True, default=0, null=True)),
                ('fetch', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('master_evaluation_element', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.MasterEvaluationElement')),
                ('section', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.Section')),
            ],
        ),
    ]
