# Generated by Django 3.0.5 on 2020-08-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0002_auto_20200807_1023"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluation",
            name="name",
            field=models.CharField(default="Evaluation 09/08/2020", max_length=200),
        ),
    ]
