# Generated by Django 3.0.5 on 2020-08-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0003_auto_20200809_1341"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluation",
            name="name",
            field=models.CharField(default="Evaluation 31/08/2020", max_length=200),
        ),
        migrations.AlterField(
            model_name="externallink",
            name="type",
            field=models.CharField(
                choices=[
                    ("web article", "web article"),
                    ("academic paper", "academic paper"),
                    ("software", "software"),
                    ("technical guide", "technical guide"),
                    ("tool", "tool"),
                    ("code repository", "code repository"),
                    ("public declaration", "public declaration"),
                    ("official report", "official report"),
                ],
                default="web_article",
                max_length=500,
            ),
        ),
    ]
