# Generated by Django 3.0.5 on 2020-09-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_auto_20200831_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externallink',
            name='additional_text',
        ),
        migrations.RemoveField(
            model_name='externallink',
            name='link',
        ),
        migrations.RemoveField(
            model_name='externallink',
            name='name',
        ),
        migrations.RemoveField(
            model_name='externallink',
            name='type',
        ),
        migrations.AddField(
            model_name='externallink',
            name='text',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='name',
            field=models.CharField(default='Evaluation 02/09/2020', max_length=200),
        ),
    ]
