# Generated by Django 3.0.5 on 2021-06-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_auto_20210405_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationelement',
            name='user_justification',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
    ]
