# Generated by Django 3.0.5 on 2020-09-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_auto_20200902_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallink',
            name='type',
            field=models.CharField(choices=[('web article', 'web article'), ('academic paper', 'academic paper'), ('software', 'software'), ('technical guide', 'technical guide'), ('tool', 'tool'), ('code repository', 'code repository'), ('public declaration', 'public declaration'), ('official report', 'official report')], default='web_article', max_length=500),
        ),
    ]
