# Generated by Django 3.0.5 on 2021-06-23 21:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_evaluationelement_user_justification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationelement',
            name='user_justification',
            field=ckeditor.fields.RichTextField(blank=True, max_length=20000, null=True),
        ),
    ]
