# Generated by Django 3.2.7 on 2021-09-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_auto_20210623_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationelementweight',
            name='master_evaluation_element_weight_json',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='evaluationscore',
            name='exposition_dic',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='scoringsystem',
            name='master_choices_weight_json',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='upgrade_json',
            field=models.JSONField(),
        ),
    ]
