# Generated by Django 3.0.5 on 2020-09-16 13:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_auto_20200904_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='name',
            field=models.CharField(default='Evaluation 16/09/2020', max_length=200),
        ),
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upgrade_json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('final_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_assessment', to='assessment.Assessment')),
                ('origin_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_assessment', to='assessment.Assessment')),
            ],
        ),
    ]
