# Generated by Django 3.2.7 on 2021-09-03 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_auto_20210901_1353'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER TABLE assessment_evaluationscore ALTER COLUMN exposition_dic '
            'TYPE jsonb USING exposition_dic::text::jsonb;'
        ),
    ]
