# Generated by Django 3.2.7 on 2021-09-06 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_auto_20210903_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='previous_assessment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.assessment'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='upgraded_from',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_upgraded_from', to='assessment.assessment'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_assessment', to='assessment.assessment'),
        ),
        migrations.CreateModel(
            name='ElementChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edito', models.TextField(blank=True, null=True)),
                ('edito_en', models.TextField(blank=True, null=True)),
                ('edito_fr', models.TextField(blank=True, null=True)),
                ('pastille', models.CharField(max_length=200)),
                ('pastille_en', models.CharField(max_length=200, null=True)),
                ('pastille_fr', models.CharField(max_length=200, null=True)),
                ('eval_element_numbering', models.CharField(max_length=200)),
                ('visibility', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_assessment', to='assessment.assessment')),
                ('previous_assessment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_assessment', to='assessment.assessment')),
            ],
        ),
    ]
