# Generated by Django 3.2.7 on 2021-11-07 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0009_labelling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='assessment.assessment'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='upgraded_from',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_upgraded_from', to='assessment.assessment'),
        ),
    ]
