# Generated by Django 3.2.7 on 2021-11-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0010_auto_20211107_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationelement',
            name='is_in_action_plan',
            field=models.BooleanField(default=False),
        ),
    ]
