# Generated by Django 3.0.5 on 2020-09-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0010_auto_20200916_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='fetch',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='evaluationelement',
            name='fetch',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='fetch',
            field=models.BooleanField(default=True),
        ),
    ]
