# Generated by Django 3.0.5 on 2020-10-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0011_auto_20200916_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='name',
            field=models.CharField(default='Evaluation 26/10/2020', max_length=200),
        ),
    ]
