# Generated by Django 3.0.5 on 2020-10-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0011_auto_20200916_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterchoice',
            name='depends_on',
        ),
        migrations.AddField(
            model_name='masterchoice',
            name='is_concerned_switch',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='name',
            field=models.CharField(default='Evaluation 22/10/2020', max_length=200),
        ),
    ]
