# Generated by Django 3.0.5 on 2020-10-29 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0012_auto_20201026_1553'),
        ('assessment', '0012_auto_20201022_1306'),
    ]

    operations = [
    ]
