# Generated by Django 3.0.5 on 2020-11-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0013_merge_20201029_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='name',
            field=models.CharField(default='Evaluation 04/11/2020', max_length=200),
        ),
    ]
