# Generated by Django 3.0.5 on 2020-11-05 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0014_auto_20201104_1433'),
        ('assessment', '0014_auto_20201104_1659'),
    ]

    operations = [
    ]
