# Generated by Django 3.0.5 on 2020-11-12 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0015_merge_20201105_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluation',
            name='score',
        ),
        migrations.AddField(
            model_name='evaluationelement',
            name='max_points',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='max_points',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='name',
            field=models.CharField(default='Evaluation 12/11/2020', max_length=200),
        ),
        migrations.CreateModel(
            name='EvaluationScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need_to_calculate', models.BooleanField(default=True)),
                ('max_points', models.FloatField(blank=True, default=0, null=True)),
                ('coefficient_scoring_system', models.FloatField(blank=True, default=0, null=True)),
                ('points_not_concerned', models.FloatField(blank=True, default=0, null=True)),
                ('points_obtained', models.FloatField(blank=True, default=0, null=True)),
                ('points_to_dilate', models.FloatField(blank=True, default=0, null=True)),
                ('dilatation_factor', models.FloatField(blank=True, default=0, null=True)),
                ('score', models.FloatField(blank=True, default=0, null=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Evaluation')),
            ],
        ),
    ]
