# Generated by Django 3.0.5 on 2020-11-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0016_auto_20201112_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationscore',
            name='need_to_set_max_points',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='name',
            field=models.CharField(default='Evaluation 16/11/2020', max_length=200),
        ),
    ]
