# Generated by Django 3.0.5 on 2020-11-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0017_auto_20201116_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='name',
            field=models.CharField(default='Evaluation 17/11/2020', max_length=200),
        ),
    ]
