# Generated by Django 3.0.5 on 2020-11-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0018_auto_20201117_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='name',
            field=models.CharField(default='Evaluation 26/11/2020', max_length=200),
        ),
    ]
