# Generated by Django 3.0.5 on 2020-11-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0019_auto_20201126_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='name',
            field=models.CharField(default='Evaluation 30/11/2020', max_length=200),
        ),
    ]
