# Generated by Django 3.0.5 on 2020-12-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0020_auto_20201130_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersection',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mastersection',
            name='name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='name',
            field=models.CharField(default='Evaluation 03/12/2020', max_length=200),
        ),
    ]
