# Generated by Django 3.0.5 on 2020-12-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0021_auto_20201203_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastersection',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='mastersection',
            name='name_fr',
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='name',
            field=models.CharField(default='Evaluation 08/12/2020', max_length=200),
        ),
    ]
