# Generated by Django 3.0.5 on 2020-12-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0022_auto_20201208_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='name',
            field=models.CharField(default='Evaluation 09/12/2020', max_length=200),
        ),
    ]
