# Generated by Django 3.0.5 on 2020-12-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0023_auto_20201209_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallink',
            name='text_en',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='externallink',
            name='text_fr',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='masterchoice',
            name='answer_text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='masterchoice',
            name='answer_text_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='masterevaluationelement',
            name='explanation_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterevaluationelement',
            name='explanation_text_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterevaluationelement',
            name='name_en',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='masterevaluationelement',
            name='name_fr',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='masterevaluationelement',
            name='question_text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='masterevaluationelement',
            name='question_text_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mastersection',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mastersection',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mastersection',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mastersection',
            name='name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='name',
            field=models.CharField(default='Evaluation 11/12/2020', max_length=200),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='name',
            field=models.CharField(default='Evaluation', max_length=200),
        ),
    ]
