# Generated by Django 3.0.5 on 2020-12-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0024_auto_20201211_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='name',
            field=models.CharField(default='Evaluation 15/12/2020', max_length=200),
        ),
    ]
