# Generated by Django 3.0.5 on 2021-01-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0026_auto_20201223_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersection',
            name='keyword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mastersection',
            name='keyword_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mastersection',
            name='keyword_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
