# Generated by Django 3.0.5 on 2021-02-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0031_auto_20210215_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallink',
            name='type',
            field=models.CharField(default='Web article', max_length=500),
        ),
    ]
