# Generated by Django 3.0.5 on 2021-02-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0032_auto_20210224_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationelement',
            name='user_notes_archived',
            field=models.BooleanField(default=False),
        ),
    ]
