# Generated by Django 3.0.5 on 2021-02-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0032_evaluationelement_user_notes_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationelement',
            name='user_notes_archived',
        ),
    ]
