# Generated by Django 3.0.5 on 2021-02-24 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0034_evaluationelement_user_notes_archived'),
        ('assessment', '0032_auto_20210224_1201'),
    ]

    operations = [
    ]
