# Generated by Django 3.0.5 on 2021-03-03 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0035_merge_20210224_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationelement',
            name='user_notes_archived',
        ),
    ]
