# Generated by Django 3.0.5 on 2021-03-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0036_remove_evaluationelement_user_notes_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationelement',
            name='user_notes_archived',
            field=models.BooleanField(default=False),
        ),
    ]
